AllCops:
  Exclude:
    - db/**/*
    - config/**/*
    - script/**/*
    - bin/**/*
    - node_modules/**/*

  EnabledByDefault: true

Style/Copyright:
  Enabled: false

Bundler/GemComment:
  Enabled: false

Lint/ConstantResolution:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Metrics/AbcSize:
  Enabled: true
  Max: 30

Metrics/MethodLength:
  Enabled: true
  Max: 20
